spring.application.name=stockSync

# A URL deve ter 'jdbc:' no inicio.
# Se estiver no Render, usa a variavel DB_URL. Se nao, usa este padrao (que so funciona la dentro).
spring.datasource.url=${DB_URL:jdbc:postgresql://stock_sync_user:7e1WB3LM9fmWUBxfoIUQMqfbwWageNqA@dpg-d4i6scidbo4c73brhm8g-a/stock_sync}
spring.datasource.username=${DB_USERNAME:stock_sync_user}
spring.datasource.password=${DB_PASSWORD:7e1WB3LM9fmWUBxfoIUQMqfbwWageNqA}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:minha_chave_privada_do_JWT}
