spring.application.name=stockSync

# Usa variáveis de ambiente (com valores padrão para localhost após o :)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/stock_sync}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# A chave JWT também deve vir do ambiente por segurança
api.security.token.secret=${JWT_SECRET:minha_chave_privada_do_JWT}